// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package grpcAccount

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	Type                 int32    `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	AccessLevel          int32    `protobuf:"varint,2,opt,name=AccessLevel,proto3" json:"AccessLevel,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	ID                   string   `protobuf:"bytes,4,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Account) GetAccessLevel() int32 {
	if m != nil {
		return m.AccessLevel
	}
	return 0
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type AccountRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRequest) Reset()         { *m = AccountRequest{} }
func (m *AccountRequest) String() string { return proto.CompactTextString(m) }
func (*AccountRequest) ProtoMessage()    {}
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *AccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRequest.Unmarshal(m, b)
}
func (m *AccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRequest.Marshal(b, m, deterministic)
}
func (m *AccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRequest.Merge(m, src)
}
func (m *AccountRequest) XXX_Size() int {
	return xxx_messageInfo_AccountRequest.Size(m)
}
func (m *AccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRequest proto.InternalMessageInfo

func (m *AccountRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AccountRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type SuccessResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuccessResponse) Reset()         { *m = SuccessResponse{} }
func (m *SuccessResponse) String() string { return proto.CompactTextString(m) }
func (*SuccessResponse) ProtoMessage()    {}
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *SuccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuccessResponse.Unmarshal(m, b)
}
func (m *SuccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuccessResponse.Marshal(b, m, deterministic)
}
func (m *SuccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuccessResponse.Merge(m, src)
}
func (m *SuccessResponse) XXX_Size() int {
	return xxx_messageInfo_SuccessResponse.Size(m)
}
func (m *SuccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SuccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SuccessResponse proto.InternalMessageInfo

func (m *SuccessResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Account)(nil), "grpcAccount.Account")
	proto.RegisterType((*AccountRequest)(nil), "grpcAccount.AccountRequest")
	proto.RegisterType((*SuccessResponse)(nil), "grpcAccount.SuccessResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x14, 0x74, 0x63, 0xb5, 0xfa, 0x4a, 0x23, 0x3c, 0x3c, 0x2c, 0xd5, 0x43, 0xc8, 0xa9, 0x20, 0xe4,
	0xa0, 0xfe, 0x40, 0xb1, 0x15, 0x02, 0xe2, 0x61, 0xd5, 0x0f, 0xa8, 0xdb, 0x41, 0x0a, 0xb6, 0xbb,
	0xee, 0x6e, 0x02, 0xfe, 0xae, 0x5f, 0x22, 0xae, 0x89, 0xa6, 0x92, 0x9b, 0xb7, 0xd9, 0x99, 0x79,
	0x33, 0x6f, 0x79, 0x34, 0xf6, 0x70, 0xf5, 0x5a, 0xa3, 0xb0, 0xce, 0x04, 0xc3, 0xa3, 0x17, 0x67,
	0xf5, 0x4c, 0x6b, 0x53, 0x6d, 0x43, 0xae, 0x69, 0xd8, 0x40, 0x66, 0x1a, 0x3c, 0xbe, 0x5b, 0x48,
	0x91, 0x89, 0xe9, 0x81, 0x8a, 0x98, 0x33, 0x1a, 0xcd, 0xb4, 0x86, 0xf7, 0x77, 0xa8, 0xf1, 0x2a,
	0x93, 0x28, 0x75, 0xa9, 0xaf, 0xa9, 0xfb, 0xe5, 0x06, 0x72, 0x3f, 0x13, 0xd3, 0x63, 0x15, 0x31,
	0xa7, 0x94, 0x94, 0x73, 0x39, 0x88, 0x4c, 0x52, 0xce, 0xf3, 0x6b, 0x4a, 0x9b, 0x12, 0x85, 0xb7,
	0x0a, 0x3e, 0x34, 0x0e, 0xd1, 0x3a, 0x7e, 0xba, 0x93, 0xdf, 0xee, 0xfc, 0x82, 0x4e, 0x1e, 0xaa,
	0xd8, 0xa4, 0xe0, 0xad, 0xd9, 0x7a, 0xb0, 0xa4, 0x61, 0x43, 0xc5, 0xd9, 0x23, 0xd5, 0x3e, 0x2f,
	0x3f, 0x04, 0x75, 0xff, 0xc5, 0x0b, 0x4a, 0x15, 0x82, 0x5b, 0xa3, 0xc6, 0xad, 0x33, 0x9b, 0x72,
	0xc5, 0x67, 0x45, 0x47, 0x2f, 0x76, 0xf7, 0x99, 0x9c, 0xf6, 0x89, 0xf9, 0x1e, 0x2f, 0x68, 0xfc,
	0x64, 0x57, 0xcb, 0x80, 0x36, 0xb7, 0xd7, 0x38, 0x39, 0xdf, 0x61, 0xff, 0x6c, 0xfd, 0x1d, 0x73,
	0xe3, 0xf0, 0xdf, 0x98, 0xe7, 0xc3, 0x78, 0xc0, 0xab, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x41,
	0xa7, 0x0d, 0x6d, 0xd1, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrpcAccountClient is the client API for GrpcAccount service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcAccountClient interface {
	RetrieveFromId(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*Account, error)
	UpdateAccount(ctx context.Context, in *Account, opts ...grpc.CallOption) (*SuccessResponse, error)
	CreateAccount(ctx context.Context, in *Account, opts ...grpc.CallOption) (*SuccessResponse, error)
}

type grpcAccountClient struct {
	cc *grpc.ClientConn
}

func NewGrpcAccountClient(cc *grpc.ClientConn) GrpcAccountClient {
	return &grpcAccountClient{cc}
}

func (c *grpcAccountClient) RetrieveFromId(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/grpcAccount.grpcAccount/RetrieveFromId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcAccountClient) UpdateAccount(ctx context.Context, in *Account, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/grpcAccount.grpcAccount/UpdateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcAccountClient) CreateAccount(ctx context.Context, in *Account, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/grpcAccount.grpcAccount/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcAccountServer is the server API for GrpcAccount service.
type GrpcAccountServer interface {
	RetrieveFromId(context.Context, *AccountRequest) (*Account, error)
	UpdateAccount(context.Context, *Account) (*SuccessResponse, error)
	CreateAccount(context.Context, *Account) (*SuccessResponse, error)
}

// UnimplementedGrpcAccountServer can be embedded to have forward compatible implementations.
type UnimplementedGrpcAccountServer struct {
}

func (*UnimplementedGrpcAccountServer) RetrieveFromId(ctx context.Context, req *AccountRequest) (*Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveFromId not implemented")
}
func (*UnimplementedGrpcAccountServer) UpdateAccount(ctx context.Context, req *Account) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccount not implemented")
}
func (*UnimplementedGrpcAccountServer) CreateAccount(ctx context.Context, req *Account) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}

func RegisterGrpcAccountServer(s *grpc.Server, srv GrpcAccountServer) {
	s.RegisterService(&_GrpcAccount_serviceDesc, srv)
}

func _GrpcAccount_RetrieveFromId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcAccountServer).RetrieveFromId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcAccount.grpcAccount/RetrieveFromId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcAccountServer).RetrieveFromId(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcAccount_UpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcAccountServer).UpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcAccount.grpcAccount/UpdateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcAccountServer).UpdateAccount(ctx, req.(*Account))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcAccount_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcAccountServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcAccount.grpcAccount/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcAccountServer).CreateAccount(ctx, req.(*Account))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcAccount_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcAccount.grpcAccount",
	HandlerType: (*GrpcAccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrieveFromId",
			Handler:    _GrpcAccount_RetrieveFromId_Handler,
		},
		{
			MethodName: "UpdateAccount",
			Handler:    _GrpcAccount_UpdateAccount_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _GrpcAccount_CreateAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
