// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	DeviceID             string   `protobuf:"bytes,3,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Request) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Request) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

type Response struct {
	Duration             float32                     `protobuf:"fixed32,1,opt,name=Duration,proto3" json:"Duration,omitempty"`
	ContextResponses     []*Response_ContextResponse `protobuf:"bytes,2,rep,name=ContextResponses,proto3" json:"ContextResponses,omitempty"`
	Error                string                      `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetDuration() float32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Response) GetContextResponses() []*Response_ContextResponse {
	if m != nil {
		return m.ContextResponses
	}
	return nil
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Response_ContextResponse struct {
	Duration             float32  `protobuf:"fixed32,1,opt,name=Duration,proto3" json:"Duration,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	GphType              int32    `protobuf:"varint,3,opt,name=GphType,proto3" json:"GphType,omitempty"`
	Gph                  string   `protobuf:"bytes,4,opt,name=Gph,proto3" json:"Gph,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_ContextResponse) Reset()         { *m = Response_ContextResponse{} }
func (m *Response_ContextResponse) String() string { return proto.CompactTextString(m) }
func (*Response_ContextResponse) ProtoMessage()    {}
func (*Response_ContextResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1, 0}
}

func (m *Response_ContextResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_ContextResponse.Unmarshal(m, b)
}
func (m *Response_ContextResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_ContextResponse.Marshal(b, m, deterministic)
}
func (m *Response_ContextResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_ContextResponse.Merge(m, src)
}
func (m *Response_ContextResponse) XXX_Size() int {
	return xxx_messageInfo_Response_ContextResponse.Size(m)
}
func (m *Response_ContextResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_ContextResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Response_ContextResponse proto.InternalMessageInfo

func (m *Response_ContextResponse) GetDuration() float32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Response_ContextResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response_ContextResponse) GetGphType() int32 {
	if m != nil {
		return m.GphType
	}
	return 0
}

func (m *Response_ContextResponse) GetGph() string {
	if m != nil {
		return m.Gph
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*Response_ContextResponse)(nil), "Response.ContextResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x49, 0x42, 0x9b, 0xf4, 0x10, 0x22, 0xb2, 0x10, 0x32, 0x99, 0xaa, 0x4c, 0x65, 0xc9,
	0x50, 0xc4, 0x13, 0x34, 0x55, 0xd5, 0x81, 0xc5, 0x80, 0x98, 0x43, 0x74, 0x6a, 0x3b, 0x10, 0x9b,
	0xbb, 0x2b, 0x82, 0x37, 0x67, 0x44, 0x35, 0x49, 0x04, 0x41, 0xea, 0xe6, 0xcf, 0xf7, 0xf9, 0x7c,
	0xfe, 0x0d, 0xe7, 0x8c, 0xf4, 0xbe, 0xab, 0xb1, 0x70, 0x64, 0xc5, 0xe6, 0xcf, 0x10, 0x1b, 0x7c,
	0xdb, 0x23, 0x8b, 0xd2, 0x10, 0xdf, 0x23, 0x73, 0xb5, 0x41, 0x1d, 0x4c, 0x83, 0xd9, 0xc4, 0x74,
	0xa8, 0xae, 0x60, 0xfc, 0xc4, 0x48, 0xeb, 0x52, 0x87, 0xbe, 0xd0, 0x92, 0xca, 0x20, 0x29, 0xf1,
	0xd0, 0x6c, 0x5d, 0xea, 0xc8, 0x57, 0x7a, 0xce, 0xbf, 0x02, 0x48, 0x0c, 0xb2, 0xb3, 0x0d, 0xa3,
	0x17, 0xf7, 0x54, 0xc9, 0xce, 0x36, 0xbe, 0x77, 0x68, 0x7a, 0x56, 0x4b, 0x48, 0x17, 0xb6, 0x11,
	0xfc, 0x90, 0x4e, 0x67, 0x1d, 0x4e, 0xa3, 0xd9, 0xd9, 0xfc, 0xba, 0xe8, 0x76, 0x8a, 0x81, 0x61,
	0xfe, 0x1d, 0x51, 0x97, 0x30, 0x5a, 0x12, 0x59, 0x6a, 0x07, 0xf9, 0x81, 0x8c, 0xe1, 0x62, 0x60,
	0x1e, 0x9d, 0xe5, 0x57, 0x04, 0xe1, 0xdf, 0x08, 0x34, 0xc4, 0x2b, 0xb7, 0x7d, 0xfc, 0x74, 0xe8,
	0x2f, 0x18, 0x99, 0x0e, 0x55, 0x0a, 0xd1, 0xca, 0x6d, 0xf5, 0xa9, 0xf7, 0x0f, 0xcb, 0xf9, 0x1d,
	0x24, 0x1b, 0x72, 0xf5, 0xc2, 0x12, 0xaa, 0x1b, 0x48, 0x1d, 0xd9, 0x1a, 0x99, 0x1f, 0xa4, 0x12,
	0x7c, 0xc5, 0x46, 0x54, 0x52, 0xb4, 0x91, 0x67, 0x93, 0xfe, 0x85, 0xf9, 0xc9, 0xcb, 0xd8, 0xff,
	0xc8, 0xed, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x69, 0x48, 0x88, 0x35, 0xa2, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrpcCoreClient is the client API for GrpcCore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcCoreClient interface {
	ProcessStatement(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type grpcCoreClient struct {
	cc *grpc.ClientConn
}

func NewGrpcCoreClient(cc *grpc.ClientConn) GrpcCoreClient {
	return &grpcCoreClient{cc}
}

func (c *grpcCoreClient) ProcessStatement(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/grpcCore/processStatement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcCoreServer is the server API for GrpcCore service.
type GrpcCoreServer interface {
	ProcessStatement(context.Context, *Request) (*Response, error)
}

// UnimplementedGrpcCoreServer can be embedded to have forward compatible implementations.
type UnimplementedGrpcCoreServer struct {
}

func (*UnimplementedGrpcCoreServer) ProcessStatement(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessStatement not implemented")
}

func RegisterGrpcCoreServer(s *grpc.Server, srv GrpcCoreServer) {
	s.RegisterService(&_GrpcCore_serviceDesc, srv)
}

func _GrpcCore_ProcessStatement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcCoreServer).ProcessStatement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcCore/ProcessStatement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcCoreServer).ProcessStatement(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcCore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcCore",
	HandlerType: (*GrpcCoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "processStatement",
			Handler:    _GrpcCore_ProcessStatement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
