// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package grpcProfile

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreationResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreationResponse) Reset()         { *m = CreationResponse{} }
func (m *CreationResponse) String() string { return proto.CompactTextString(m) }
func (*CreationResponse) ProtoMessage()    {}
func (*CreationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *CreationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreationResponse.Unmarshal(m, b)
}
func (m *CreationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreationResponse.Marshal(b, m, deterministic)
}
func (m *CreationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreationResponse.Merge(m, src)
}
func (m *CreationResponse) XXX_Size() int {
	return xxx_messageInfo_CreationResponse.Size(m)
}
func (m *CreationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreationResponse proto.InternalMessageInfo

func (m *CreationResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ProfileRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileRequest) Reset()         { *m = ProfileRequest{} }
func (m *ProfileRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileRequest) ProtoMessage()    {}
func (*ProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *ProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileRequest.Unmarshal(m, b)
}
func (m *ProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileRequest.Marshal(b, m, deterministic)
}
func (m *ProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileRequest.Merge(m, src)
}
func (m *ProfileRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileRequest.Size(m)
}
func (m *ProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileRequest proto.InternalMessageInfo

func (m *ProfileRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type Profile struct {
	BlockAddress         string   `protobuf:"bytes,1,opt,name=BlockAddress,proto3" json:"BlockAddress,omitempty"`
	AccountID            string   `protobuf:"bytes,2,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	CreatedOn            int64    `protobuf:"varint,3,opt,name=CreatedOn,proto3" json:"CreatedOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetBlockAddress() string {
	if m != nil {
		return m.BlockAddress
	}
	return ""
}

func (m *Profile) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *Profile) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func init() {
	proto.RegisterType((*CreationResponse)(nil), "grpcProfile.CreationResponse")
	proto.RegisterType((*ProfileRequest)(nil), "grpcProfile.ProfileRequest")
	proto.RegisterType((*Profile)(nil), "grpcProfile.Profile")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x2f, 0x2a, 0x48, 0x0e,
	0x28, 0xca, 0x4f, 0xcb, 0xcc, 0x49, 0x55, 0xd2, 0xe1, 0x12, 0x70, 0x2e, 0x4a, 0x4d, 0x2c, 0xc9,
	0xcc, 0xcf, 0x0b, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x92, 0xe0, 0x62, 0x0f, 0x2e,
	0x4d, 0x4e, 0x4e, 0x2d, 0x2e, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x08, 0x82, 0x71, 0x95, 0x14,
	0xb8, 0xf8, 0xa0, 0x1a, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xf8, 0xb8, 0x98, 0x3c,
	0x5d, 0xc0, 0xca, 0x38, 0x83, 0x98, 0x3c, 0x5d, 0x94, 0x32, 0xb9, 0xd8, 0xa1, 0x2a, 0x84, 0x94,
	0xb8, 0x78, 0x9c, 0x72, 0xf2, 0x93, 0xb3, 0x1d, 0x53, 0x52, 0x8a, 0x60, 0x66, 0x71, 0x06, 0xa1,
	0x88, 0x09, 0xc9, 0x70, 0x71, 0x3a, 0x26, 0x27, 0xe7, 0x97, 0xe6, 0x95, 0x78, 0xba, 0x48, 0x30,
	0x81, 0x15, 0x20, 0x04, 0x40, 0xb2, 0x60, 0xc7, 0xa5, 0xa6, 0xf8, 0xe7, 0x49, 0x30, 0x2b, 0x30,
	0x6a, 0x30, 0x07, 0x21, 0x04, 0x8c, 0x96, 0x30, 0x72, 0x21, 0x7b, 0x45, 0xc8, 0x97, 0x4b, 0xcc,
	0x2d, 0x33, 0x2f, 0x05, 0xca, 0x75, 0xaa, 0x44, 0x98, 0x23, 0xad, 0x87, 0xa4, 0x4e, 0x0f, 0xd5,
	0x07, 0x52, 0x22, 0xd8, 0x24, 0x95, 0x18, 0x84, 0xdc, 0xb8, 0x78, 0x21, 0x76, 0xc1, 0xcc, 0xc7,
	0xaa, 0x50, 0x4a, 0x16, 0x45, 0x14, 0x3d, 0x2c, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0xa1, 0x6e, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x78, 0xb3, 0x9a, 0x9d, 0x86, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrpcProfileClient is the client API for GrpcProfile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcProfileClient interface {
	FindProfileByAccountID(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*Profile, error)
	CreateProfile(ctx context.Context, in *Profile, opts ...grpc.CallOption) (*CreationResponse, error)
}

type grpcProfileClient struct {
	cc *grpc.ClientConn
}

func NewGrpcProfileClient(cc *grpc.ClientConn) GrpcProfileClient {
	return &grpcProfileClient{cc}
}

func (c *grpcProfileClient) FindProfileByAccountID(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, "/grpcProfile.grpcProfile/FindProfileByAccountID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcProfileClient) CreateProfile(ctx context.Context, in *Profile, opts ...grpc.CallOption) (*CreationResponse, error) {
	out := new(CreationResponse)
	err := c.cc.Invoke(ctx, "/grpcProfile.grpcProfile/CreateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcProfileServer is the server API for GrpcProfile service.
type GrpcProfileServer interface {
	FindProfileByAccountID(context.Context, *ProfileRequest) (*Profile, error)
	CreateProfile(context.Context, *Profile) (*CreationResponse, error)
}

// UnimplementedGrpcProfileServer can be embedded to have forward compatible implementations.
type UnimplementedGrpcProfileServer struct {
}

func (*UnimplementedGrpcProfileServer) FindProfileByAccountID(ctx context.Context, req *ProfileRequest) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindProfileByAccountID not implemented")
}
func (*UnimplementedGrpcProfileServer) CreateProfile(ctx context.Context, req *Profile) (*CreationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProfile not implemented")
}

func RegisterGrpcProfileServer(s *grpc.Server, srv GrpcProfileServer) {
	s.RegisterService(&_GrpcProfile_serviceDesc, srv)
}

func _GrpcProfile_FindProfileByAccountID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcProfileServer).FindProfileByAccountID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcProfile.grpcProfile/FindProfileByAccountID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcProfileServer).FindProfileByAccountID(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcProfile_CreateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Profile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcProfileServer).CreateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcProfile.grpcProfile/CreateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcProfileServer).CreateProfile(ctx, req.(*Profile))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcProfile_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcProfile.grpcProfile",
	HandlerType: (*GrpcProfileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindProfileByAccountID",
			Handler:    _GrpcProfile_FindProfileByAccountID_Handler,
		},
		{
			MethodName: "CreateProfile",
			Handler:    _GrpcProfile_CreateProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
